name: munch_yum
description: "A new Flutter project."


publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.4

#------------------- PACKAGES --------------------#


dependencies:
  flutter:
    sdk: flutter

  # Utility Packages
  url_launcher: ^6.3.2
  intl: ^0.20.2
  http: ^1.6.0
  logger: ^2.7.0
  flutter_native_splash: ^2.4.7
  smooth_page_indicator: ^2.0.1
  badges: ^3.2.0

  # Icons
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8


  # State Management
  get: ^4.7.3
  get_storage: ^2.1.1


  # Product Specific



  #---------------- ./ PACKAGES END ---------------#

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0





flutter:
  uses-material-design: true

  #----------------- LOCAL ASSETS ------------------#
  assets:
    - assets/fonts/
    - assets/icons/
    - assets/images/
    - assets/logos/
    - assets/images/onboarding/
    - assets/images/login/
    - assets/images/banners/
    - assets/icons/avatars/
    - assets/icons/icons/
    - assets/images/categories/
    - assets/images/menu/
    - assets/images/offers/


  #------------------- LOCAL FONTS ----------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800



  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
